apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flightsearch-app
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: mini-dcp-project
  source:
    path: gitops
    repoURL: https://github.com/OliverJochum/mini-dcp.git
    targetRevision: HEAD
    kustomize: {}
  syncPolicy:
    automated:
      prune: true