name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flightsearch-app
    steps:
     - name: Checkout Code
       uses: actions/checkout@v2
     - name: Setup Java
       uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: 21
     - name: Setup Gradle and Validate Wrapper
       uses: gradle/actions/setup-gradle@v4
     - name: Install & Build
       run: ./gradlew clean build
     - name: Run tests
       run: ./gradlew test
